version: '3.8'

services:
    user:
        build:
            context: ./userService
        image: microservice/demo/user
        restart: "no"
        environment:
            - DB_URI=mongodb://mongo:27017/
            - DB_NAME=Microservice-demo-user
        ports:
            - 8080:50051
        depends_on:
            - mongo

    userinterface:
        build:
            context: ./userInterface
        image: microservice/demo/userinterface
        restart: "no"
        environment:
            NODE_ENV: development
            CHOKIDAR_USEPOLLING: 'true'
        ports:
            - 8092:8092
        depends_on:
            - uibackend
        volumes:
            -  ./userInterface/src:/app/src
            -  /app/node_modules

    project:
        build:
            context: ./projectService
        image: microservice/demo/project
        restart: "no"
        environment:
            - DB_URI=mysql+mysqldb://root:password@mysql:3306/microservice-project
        ports:
            - 8081:50052
        depends_on:
            - mysql
            - user

    task:
        build:
            context: ./taskService
        image: microservice/demo/task
        restart: "no"
        entrypoint: [./init]
        environment:
            - USER_ADDRESS=user:50051
            - PROJECT_ADDRESS=project:50052
            - DB_URI=postgres://postgres:password@postgresql:5432/microservice-task
        ports:
            - 8082:50053
        depends_on:
            - postgresql
            - user
            - project


    postgresql:
        image: postgres
        restart: "no"
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: microservice-task
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes:
            - postgresdb:/var/lib/postgresql/data/

    mysql:
        image: mysql:5.7
        restart: "no"
        environment:
            MYSQL_DATABASE: microservice-project
            MYSQL_ROOT_PASSWORD: password
        ports:
            - 3306:3306
        volumes:
            - mysqldb:/var/lib/mysql
            - ./uiBackend/db_data:/docker-entrypoint-initdb.d

    mongo:
        image: mongo
        restart: "no"
        environment:
            MONGO_INITDB_DATABASE: Microservice-demo-user
        ports:
            - 27017:27017
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb

    gmailapi:
        build:
            context: ./gmailapi
        image: microservice/demo/gmailapi
        restart: "no"
        environment:
            MONGO_INITDB_DATABASE: Microservice-demo-user
        ports:
            - 8084:50054
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        depends_on:
            - mongo

    igapi:
        build:
            context: ./igapi
        image: microservice/demo/igapi
        restart: "no"
        environment:
            MONGO_INITDB_DATABASE: Microservice-demo-user
        ports:
            - 8087:50055
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        depends_on:
            - mongo

    uibackend:
        build:
            context: ./uiBackend
        image: microservice/demo/uibackend
        restart: "no"
        environment:
            - DB_URI=mysql+mysqldb://root:password@mysql:3306/products
        ports:
            - 3070:3070
        depends_on:
            - mysql

    api:
        build:
            context: ./apiService
        image: microservice/demo/api
        restart: "no"
        environment:
            - USER_ADDRESS=user:50051
            - PROJECT_ADDRESS=project:50052
            - TASK_ADDRESS=task:50053
            - GMAILAPI_ADDRESS=gmailapi:50054
            - IGAPI_ADDRESS=igapi:50055
            - USERINTERFACE_ADDRESS=userinterface:8092
            - UIBACKEND_ADDRESS=uibackend:3070
        ports:
            - 8083:50059
        command: serve
        depends_on:
            - user
            - project
            - task
            - gmailapi
            - igapi
            - uibackend
            - userinterface

    api-gateway:
        image: microservice/demo/api
        restart: "no"
        environment:
            - HOST=api
            - PORT=50059
            - PROXY_PORT=9090
        ports:
            - 9090:9090
        command: proxy
        depends_on:
            - api

volumes:
    postgresdb:
    mysqldb:
    mongodb:
    mongodb_config: